app:
  mem_limit: 300m
  memswap_limit: 1g
  build: .
  environment:
    - NODE_ENV=production
    - PORT=3000
    - LOGGER_LEVEL=silly
    - LOGGER_ENABLED=true
    - SESSION_KEY=koasess
  ports:
    - '3000:3000'
  volumes:
    - .:/home/nodejs/app
    - /home/nodejs/app/node_modules
